# Generated by Django 3.0.5 on 2020-04-26 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
                ('LateArrival', models.BooleanField(default=True)),
                ('enquiry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('extras_price', models.IntegerField()),
                ('setup4U', models.IntegerField(default=0)),
            ],
        ),
    ]
