# Generated by Django 3.0.5 on 2020-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campspot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campme',
            old_name='extras_price',
            new_name='extras',
        ),
        migrations.RemoveField(
            model_name='campme',
            name='enquiry_date',
        ),
        migrations.AddField(
            model_name='campme',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='campme',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campme',
            name='county',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campme',
            name='postcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='campme',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='campme',
            name='town',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campme',
            name='price',
            field=models.IntegerField(),
        ),
    ]
